#ifndef FUTUNER_CONFIG_H
#define FUTUNER_CONFIG_H

#define FUTUNER_VERSION_MAJOR 2
#define FUTUNER_VERSION_MINOR 0
#define FUTUNER_VERSION_PATCH 0

#define FUTUNER_VERSION_STRING "2.0.0-dev"

#define FUTUNER_NVS_NAMESPACE "futuner"

#define VIN_MAX_LENGTH 17
#define SOFTWARE_VERSION_MAX_LENGTH 32
#define HARDWARE_VERSION_MAX_LENGTH 32
#define BUILD_ID_MAX_LENGTH 64

#endif // FUTUNER_CONFIG_H
