#!/usr/bin/env python3
"""Generate a firmware-side logger catalog header from JSON.

Input:
  * A2L-derived per-(boxcode, calibration) JSON catalog
    (tools/a2l_to_catalog/dump_a2l_catalog.py output)
  * A "selected names" file (one UI-catalog name per line) — the
    subset of the full A2L catalog that this firmware build will
    expose. Lets us cap polling response size sensibly + skip
    vars the UI catalog doesn't reference.

Output:
  C header containing a constant array of logger_variable_def_t.

Schema match: firmware/src/logger/logger_variables.h
  typedef struct {
      const char *name;
      const char *display_name;
      const char *unit;
      uint32_t    address;
      uint8_t     size;
      float       scale;
      float       offset;
      bool        is_required;
      bool        is_signed;
  } logger_variable_def_t;

The UI catalog names + display + unit come from a separate "ui
catalog match" TSV (match_ui_catalog.py output) so the emitted
firmware catalog stays consistent with what the UI presents.
"""
import argparse
import csv
import json
import sys
from pathlib import Path

# Vars that the firmware logger ALWAYS includes regardless of the
# user's profile. Per-boxcode; this matches the existing
# is_required=true entries in logger_variables.c. Lives in code
# rather than the JSON catalog because is_required is a firmware-
# policy decision (not an A2L property).
REQUIRED_NAMES_BY_BOXCODE = {
    "4K0907557G__0003": {
        "nmot_w",                       # engine speed — needed for
                                        # the rev-limit guard
        "InjSys_ratEthPrtnBascFu",      # ethanol % — needed for
                                        # flex-fuel constraint logic
        "Com_stCrCtlPan",               # cruise — needed for the
                                        # WOT trigger
    },
}

C_PREAMBLE = """\
/* GENERATED — DO NOT EDIT BY HAND.
 *
 * Source:        {a2l_basename}
 * Boxcode:       {boxcode}
 * Calibration:   {calibration}
 * Generated by:  tools/a2l_to_catalog/emit_firmware.py
 * Generated at:  {timestamp}
 *
 * To regenerate, see tools/a2l_to_catalog/README.md.
 */
#ifndef LOGGER_CATALOG_{symbol}_H
#define LOGGER_CATALOG_{symbol}_H

#include "../../logger_variables.h"

static const logger_variable_def_t LOGGER_CATALOG_{symbol}[] = {{
"""

C_EPILOGUE = """\
}};

#define LOGGER_CATALOG_{symbol}_COUNT \\
    (sizeof(LOGGER_CATALOG_{symbol}) / sizeof(LOGGER_CATALOG_{symbol}[0]))

#endif  /* LOGGER_CATALOG_{symbol}_H */
"""

def fmt_float(x, default="1.0f"):
    """C float literal. Forces a decimal point so '1' becomes '1.0f'
    (bare '1f' is not a valid float literal in C — gcc rejects it)."""
    if x is None:
        return default
    s = f"{x:.10g}"
    # If g-format produced an integer-looking string (e.g. "1"), add ".0".
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s + "f"

def fmt_scale(x):
    return fmt_float(x, "1.0f")

def fmt_offset(x):
    if x is None or x == 0:
        return "0"
    return fmt_float(x, "0")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--a2l-json", required=True,
                    help="A2L catalog JSON (dump_a2l_catalog.py output)")
    ap.add_argument("--match-tsv", required=True,
                    help="UI catalog match TSV (match_ui_catalog.py output)")
    ap.add_argument("--boxcode", required=True)
    ap.add_argument("--calibration", required=True)
    ap.add_argument("--out", required=True,
                    help="Output .h path")
    ap.add_argument("--include-missing", action="store_true",
                    help="Also include UI-catalog entries that didn't match A2L "
                         "(legacy SEFI addresses). Default: skip them.")
    args = ap.parse_args()

    a2l_index = {e["name"]: e for e in json.load(open(args.a2l_json))}

    # Read match TSV: one row per UI catalog entry.
    rows = []
    with open(args.match_tsv) as f:
        rd = csv.DictReader(f, delimiter="\t")
        for row in rd:
            if row["confidence"] == "missing":
                if not args.include_missing:
                    continue
                rows.append(row)
                continue
            if row["confidence"] not in ("exact", "msg_suffix"):
                # "substring" is low-confidence; skip — flag in audit doc.
                continue
            rows.append(row)

    required = REQUIRED_NAMES_BY_BOXCODE.get(args.boxcode, set())

    # Dedupe by ui_name and resolve full A2L details from the index.
    seen = set()
    entries = []
    for row in rows:
        ui_name = row["ui_name"]
        a2l_name = row["a2l_name"]
        if ui_name in seen:
            continue
        seen.add(ui_name)
        if not a2l_name:
            continue
        a2l = a2l_index.get(a2l_name)
        if not a2l:
            print(f"WARN: a2l_name {a2l_name!r} not in A2L JSON — skipping {ui_name}",
                  file=sys.stderr)
            continue
        if a2l["scale"] is None:
            print(f"WARN: {ui_name}: no resolvable scale (compu_method={a2l.get('compu_method')}) — skipping",
                  file=sys.stderr)
            continue
        entries.append({
            "name":         ui_name,
            "display":      row["ui_display"] or ui_name,
            # UI catalog's unit field wins (Sean-curated for display).
            # Fall back to A2L unit, then empty.
            "unit":         row.get("ui_unit") or a2l.get("unit") or "",
            "address":      a2l["address"],
            "size":         a2l["size"],
            "scale":        a2l["scale"],
            "offset":       a2l["offset"] or 0,
            "is_required":  ui_name in required,
            "is_signed":    a2l["signed"],
            "a2l_name":     a2l_name,
        })

    # Sort entries with required-first (so the catalog reads
    # naturally), then by upper address.
    entries.sort(key=lambda e: (not e["is_required"], e["address"]))

    # Emit.
    import datetime
    symbol = (args.boxcode + "__" + args.calibration).replace("-", "_")
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        f.write(C_PREAMBLE.format(
            a2l_basename = Path(args.a2l_json).name,
            boxcode      = args.boxcode,
            calibration  = args.calibration,
            timestamp    = datetime.datetime.now().isoformat(timespec="seconds"),
            symbol       = symbol,
        ))
        # Width-tune the columns so the file is grep-friendly.
        for e in entries:
            req  = "true " if e["is_required"]  else "false"
            sign = "true " if e["is_signed"]    else "false"
            f.write(
                f'    {{ "{e["name"]}", '
                f'"{e["display"]}", '
                f'"{e["unit"]}", '
                f'0x{e["address"]:08X}, '
                f'{e["size"]}, '
                f'{fmt_scale(e["scale"])}, '
                f'{fmt_offset(e["offset"])}, '
                f'{req}, {sign} }},  '
                f'/* A2L: {e["a2l_name"]} */\n'
            )
        f.write(C_EPILOGUE.format(symbol=symbol))

    print(f"emitted {len(entries)} entries -> {out_path}", file=sys.stderr)

if __name__ == "__main__":
    main()
