#!/usr/bin/env python3
"""Generate the firmware DTC description table from CSV sources.

Inputs (one or more, layered in order — later sources WIN where
codes overlap):
  --csv tools/data/sae_bootstrap.csv      hand-authored bootstrap
  --csv tools/data/nhtsa_obdii.csv        NHTSA public reference (optional)
  --csv tools/data/...                    any further layers

Output:
  firmware/src/dtc/generated/dtc_descriptions.gen.c

The .gen.c file is committed. Source CSVs in tools/data/ are also
committed when the data is freely redistributable (NHTSA, the
hand-authored bootstrap). Licensed sources stay gitignored locally;
their lines still flow into the generated .c, which is the only
artifact required at build time.

P-77 L2 (this generator) extends P-77 L1 (resolve_fallback() in
dtc_feature.c). Codes in the generated table take precedence; the
fallback router runs only on a table miss.

Usage:
    sae_j2012_to_dtc_table.py \
        --csv tools/data/sae_bootstrap.csv \
        --out firmware/src/dtc/generated/dtc_descriptions.gen.c

Constraints from CLAUDE.md Rule 3: no magic numbers. All emitted
ranges and array caps come from explicit constants. The generator
fails loud on:
  - duplicate codes within a single layer (catches bootstrap copy-
    paste mistakes; layers can override across files)
  - bogus code format (regex enforced)
  - empty description
"""
import argparse
import csv
import re
import sys
from datetime import datetime
from pathlib import Path

CODE_RE = re.compile(r'^[PCBU][0-3][0-9A-F]{3}$')

C_PREAMBLE = """\
/* GENERATED — DO NOT EDIT BY HAND.
 *
 * Source CSVs (layered, later WINs):
{layers_doc}
 *
 * Generated by tools/sae_j2012_to_dtc_table.py
 * Generated at: {timestamp}
 *
 * Edit any tools/data CSV (or add a new layer) and re-run
 * tools/sae_j2012_to_dtc_table.py (or `make dtc-table`).
 */
#include "../dtc.h"

/* Provided externally so dtc_feature.c can wire this table into the
 * family-keyed lookup. The legacy hand-authored k_master_descriptions[]
 * remains as the fallback layer for codes outside this generated set. */
typedef struct {{
    const char *code;
    const char *description;
}} dtc_gen_entry_t;

const dtc_gen_entry_t DTC_GEN_DESCRIPTIONS[] = {{
"""

C_EPILOGUE = """\
};

const size_t DTC_GEN_DESCRIPTIONS_COUNT =
    sizeof(DTC_GEN_DESCRIPTIONS) / sizeof(DTC_GEN_DESCRIPTIONS[0]);
"""


def load_csv(path: Path) -> dict:
    """Return {code: description}. Rejects malformed rows loudly."""
    rows = {}
    with path.open() as f:
        rd = csv.DictReader(_strip_comments(f))
        for row in rd:
            code = (row.get("code") or "").strip()
            desc = (row.get("description") or "").strip()
            if not code or code.startswith("#"):
                continue
            if not CODE_RE.match(code):
                raise SystemExit(f"{path}:{rd.line_num}: bad code {code!r}")
            if not desc:
                raise SystemExit(f"{path}:{rd.line_num}: empty description for {code}")
            if code in rows:
                raise SystemExit(f"{path}:{rd.line_num}: duplicate {code} in this file")
            rows[code] = desc
    return rows


def _strip_comments(stream):
    """Yield lines from stream with '#'-prefix lines dropped, blanks kept
    so DictReader sees the header on line 1."""
    for line in stream:
        if line.lstrip().startswith("#"):
            continue
        yield line


def c_escape(s: str) -> str:
    """Escape for C string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", action="append", required=True,
                    help="CSV source file (repeatable; layered in order)")
    ap.add_argument("--out", required=True,
                    help="Output .gen.c path")
    args = ap.parse_args()

    layered = {}
    layer_docs = []
    for csv_path in args.csv:
        p = Path(csv_path)
        if not p.exists():
            print(f"warn: missing layer {p} — skipping", file=sys.stderr)
            layer_docs.append(f" *   {p.name:50s} (MISSING)")
            continue
        loaded = load_csv(p)
        layered.update(loaded)
        layer_docs.append(f" *   {p.name:50s} {len(loaded):>4d} codes")

    if not layered:
        sys.exit("no codes loaded from any layer; refusing to emit empty table")

    # Sort emitted entries by code so the .gen.c diff is stable.
    entries = sorted(layered.items())

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w") as f:
        f.write(C_PREAMBLE.format(
            layers_doc="\n".join(layer_docs),
            timestamp=datetime.now().isoformat(timespec="seconds"),
        ))
        for code, desc in entries:
            f.write(f'    {{ "{code}", "{c_escape(desc)}" }},\n')
        f.write(C_EPILOGUE)

    print(f"emitted {len(entries)} codes -> {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
